
# src/openapi/person.yaml
openapi: 3.1.0
info:
  title: person API
  version: 1.0.0
paths:
  /person:
    get:
      summary: Get all person
      responses:
        '200':
          description: A list of person
    post:
      summary: Create new person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Created
  /person/{id}:
    get:
      summary: Get person by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A person
    put:
      summary: Update person
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete person
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
