
# src/openapi/enter_observation.yaml
openapi: 3.1.0
info:
  title: enter_observation API
  version: 1.0.0
paths:
  /enter_observation:
    get:
      summary: Get all enter_observation
      responses:
        '200':
          description: A list of enter_observation
    post:
      summary: Create new enter_observation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Created
  /enter_observation/{id}:
    get:
      summary: Get enter_observation by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A enter_observation
    put:
      summary: Update enter_observation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete enter_observation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
